const aiCategories = new Set(["china-ai", "global-ai", "music-ai"]);
const rankingSources = {
  similarweb: { label: "Similarweb 2026-07", url: "https://www.similarweb.com/top-websites/ai-chatbots-and-tools/" },
  arenaText: { label: "Arena 文本榜", url: "https://arena.ai/leaderboard/text?styleControl=off" },
  artificialAnalysis: { label: "Artificial Analysis", url: "https://artificialanalysis.ai/models" },
  arenaVideo: { label: "Arena 视频榜", url: "https://arena.ai/leaderboard/video-edit" },
  a16z: { label: "a16z 2026 Top 100", url: "https://a16z.com/100-gen-ai-apps-6/" },
  geminiNotebook: { label: "Google 更名公告", url: "https://blog.google/innovation-and-ai/products/gemini-notebook/notebooklm-gemini-notebook/" },
  sunoStudio: { label: "Suno Studio 2.0", url: "https://suno.com/blog/studio-2" },
  sunoDownloads: { label: "Suno 下载政策", url: "https://suno.com/blog/suno-updates-tos" },
  elevenMusic: { label: "Music v2", url: "https://elevenlabs.io/blog/introducing-music-v2" },
  geminiLyria: { label: "Google Lyria", url: "https://blog.google/intl/en-ie/products/lyria-3/" },
  udioLimits: { label: "Udio 下载限制", url: "https://help.udio.com/en/articles/12683565-changes-associated-with-the-universal-music-group-umg-partnership" },
};

const aiGroupOrder = {
  "china-ai": ["通用助手", "搜索研究", "教育语音", "图像视频", "AI IDE", "编程 Agent", "Agent 框架"],
  "global-ai": ["通用助手", "研究知识", "Agent", "多模型平台", "浏览器 Agent", "AI IDE", "编程 Agent", "编程建站", "图像设计", "视频创作", "办公展示", "语音"],
  "music-ai": ["歌曲生成", "配乐素材", "音乐片段"],
};

const officialLinks = [
  {
      "name": "GitHub Copilot Coding Agent",
      "url": "https://github.com/features/copilot",
      "useCase": "编程 Agent",
      "recommendationRank": 4,
      "description": "GitHub 的编程 Agent，连接仓库、编辑器与云端任务。",
      "strength": "可从 Issue 发起任务、修改代码并提交供审查的变更。",
      "weakness": "云端任务受订阅、组织策略与仓库权限限制，合并前需要审查。",
      "bestFor": "适合：GitHub 仓库协作、Issue 到代码变更",
      "aliases": [
          "GitHub Copilot",
          "Copilot cloud agent"
      ],
      "initials": "GH",
      "iconUrl": "assets/icons/copilot.svg",
      "category": "global-ai",
      "categoryLabel": "国外 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
      "name": "Google Antigravity",
      "parentProduct": "Gemini",
      "url": "https://antigravity.google/",
      "useCase": "AI IDE",
      "moduleLabel": "编程 Agent",
      "recommendationRank": 2,
      "description": "Google 的 Agent 开发环境，用于规划、执行和检查代码任务。",
      "strength": "把代码编辑、终端执行与 Agent 协作放在同一开发流程中。",
      "weakness": "需要本地开发环境，模型额度与功能开放范围以账号为准。",
      "bestFor": "适合：Agent 驱动的项目开发",
      "aliases": [
          "Antigravity",
          "谷歌反重力"
      ],
      "initials": "AG",
      "iconUrl": "assets/icons/antigravity.png",
      "category": "global-ai",
      "categoryLabel": "国外 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
      "name": "Devin Desktop",
      "url": "https://devin.ai/desktop",
      "useCase": "AI IDE",
      "recommendationRank": 3,
      "description": "Devin 的桌面编程环境，原名 Windsurf。",
      "strength": "围绕代码库进行编辑和 Agent 协作，连接 Devin 开发工作流。",
      "weakness": "需要安装客户端；云端任务与模型使用可能受套餐限制。",
      "bestFor": "适合：桌面代码编辑与 Agent 开发",
      "aliases": [
          "Windsurf",
          "Devin",
          "Codeium"
      ],
      "initials": "Dv",
      "iconUrl": "assets/icons/devin-desktop.png",
      "category": "global-ai",
      "categoryLabel": "国外 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
      "name": "Kiro",
      "url": "https://kiro.dev/",
      "useCase": "AI IDE",
      "recommendationRank": 4,
      "description": "以规格说明和 Agent 工作流组织软件开发的编程工具。",
      "strength": "把需求、设计与实现任务关联起来，适合有明确验收要求的项目。",
      "weakness": "规格仍需开发者维护，复杂项目的生成代码需要验证。",
      "bestFor": "适合：规格驱动开发、需求到实现",
      "aliases": [
          "Kiro IDE",
          "Kiro CLI"
      ],
      "initials": "Ki",
      "iconUrl": "assets/icons/kiro.png",
      "category": "global-ai",
      "categoryLabel": "国外 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
      "name": "Cline",
      "url": "https://github.com/cline/cline",
      "useCase": "编程 Agent",
      "recommendationRank": 5,
      "description": "开源编程 Agent，提供编辑器扩展、CLI 和 SDK。",
      "strength": "支持多模型接入、文件修改与命令执行，便于定制开发流程。",
      "weakness": "需管理模型配置、调用费用与执行权限。",
      "bestFor": "适合：开源、多模型和可控的编码任务",
      "aliases": [
          "Cline CLI"
      ],
      "initials": "Cl",
      "iconUrl": "assets/icons/cline.png",
      "category": "global-ai",
      "categoryLabel": "国外 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
      "name": "Qwen Code",
      "parentProduct": "千问",
      "url": "https://github.com/QwenLM/qwen-code",
      "useCase": "编程 Agent",
      "recommendationRank": 2,
      "description": "Qwen 团队开源的终端编程 Agent。",
      "strength": "可读取项目、编辑文件并运行开发命令，适合终端工作流。",
      "weakness": "需要命令行基础，并自行检查配置、权限与代码变更。",
      "bestFor": "适合：Qwen 生态的终端编程任务",
      "aliases": [
          "千问代码",
          "Qwen CLI"
      ],
      "initials": "Qw",
      "iconUrl": "assets/icons/qwen-code.png",
      "category": "china-ai",
      "categoryLabel": "国内 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
      "name": "OpenHands",
      "url": "https://github.com/OpenHands/OpenHands",
      "useCase": "编程 Agent",
      "recommendationRank": 6,
      "description": "面向软件开发的 Agent 平台，支持本地运行与自托管。",
      "strength": "可组织代码任务与 Agent 会话，核心代码开放，方便自主部署。",
      "weakness": "自托管需要运行环境与模型配置；企业目录使用单独许可。",
      "bestFor": "适合：自托管 Agent、可定制的软件开发",
      "aliases": [
          "Open Hands",
          "Agent Canvas"
      ],
      "initials": "OH",
      "iconUrl": "assets/icons/openhands.svg",
      "category": "global-ai",
      "categoryLabel": "国外 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
      "name": "Comet Assistant",
      "parentProduct": "Perplexity",
      "url": "https://www.perplexity.ai/comet",
      "useCase": "浏览器 Agent",
      "recommendationRank": 1,
      "description": "Perplexity Comet 浏览器中的 AI 助手。",
      "strength": "结合当前网页进行问答、整理资料和辅助执行浏览器任务。",
      "weakness": "需要使用 Comet，涉及账号的操作依赖授权与人工确认。",
      "bestFor": "适合：网页阅读、资料整理与浏览器任务",
      "aliases": [
          "Comet",
          "彗星浏览器"
      ],
      "initials": "Co",
      "iconUrl": "assets/icons/comet.jpg",
      "category": "global-ai",
      "categoryLabel": "国外 AI",
      "rankingNote": "按官方产品定位与上述使用场景收录，不代表模型能力排名。",
      "sourceIds": [
          "official"
      ],
      "verifiedAt": "2026-09-05"
  },
  {
    name: "Chrome",
    description: "Google 官方 Chrome 浏览器下载与介绍。",
    url: "https://www.google.cn/chrome/",
    category: "browser",
    categoryLabel: "浏览器",
    initials: "Ch",
    color: "linear-gradient(135deg, #1a73e8, #34a853 48%, #fbbc04)",
    pinned: true,
    downloadInfo: {
      version: "Windows 安装器",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/%E8%B0%B7%E6%AD%8C%E6%B5%8F%E8%A7%88%E5%99%A8",
      upstreamUrl: "https://www.google.cn/chrome/",
      note: "CNB 中保存的 Chrome Windows 安装程序；下载 ZIP 后解压并运行 ChromeSetup.exe。",
      files: [
        {
          label: "Windows 安装器",
          platform: "Windows",
          architecture: "由安装程序自动匹配",
          format: "ZIP（内含 EXE）",
          size: "5.07 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/2437d214-fc5f-4f09-9f15-1ede2d23b328/ChromeSetup.zip",
          checksum: "de60f32c9d1f561d7fa48693b7db81d7402147ab1ee781e42169cfe08902203d",
        },
      ],
    },
  },
  {
    name: "UU 远程",
    description: "网易 UU 远程控制，适合远程办公、远程协助和游戏串流。",
    url: "https://uuyc.163.com/",
    category: "remote",
    categoryLabel: "远程控制",
    initials: "UU",
    color: "linear-gradient(135deg, #00a3ff, #0057ff)",
    pinned: true,
  },
  {
    name: "Clash Verge Rev",
    iconUrl: "assets/icons/clash-verge-rev.png",
    description: "Clash Verge 延续版本，提供跨平台代理客户端与文档入口。",
    url: "https://github.com/clash-verge-rev/clash-verge-rev",
    category: "network",
    categoryLabel: "网络工具",
    initials: "CV",
    color: "linear-gradient(135deg, #4f46e5, #06b6d4)",
    pinned: true,
    downloadInfo: {
      version: "2.5.2",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/clash-verge-rev-v2.5.2",
      upstreamUrl: "https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.5.2",
      note: "CNB 不接受 EXE/DMG 网页附件，下载 ZIP 后解压。Windows x64 与 macOS Apple 芯片是两个不同平台。",
      files: [
        {
          label: "Windows x64",
          platform: "Windows",
          architecture: "x64（Intel / AMD）",
          format: "ZIP（内含 EXE）",
          size: "44.79 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/887eb89e-4e75-4c29-bba6-aba6e339e156/Clash.Verge_2.5.2_x64-setup.exe.zip",
          checksum: "a1c9a8b41f1681f8e2d7a233cbd2a5539b692c58311ea256513316f7c3e65b48",
        },
        {
          label: "macOS Apple 芯片",
          platform: "macOS",
          architecture: "ARM64（Apple M 系列）",
          format: "ZIP（内含 DMG）",
          size: "58.11 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/0582b98d-0566-445a-b8aa-d32ccdfc5098/Clash.Verge_2.5.2_aarch64.dmg.zip",
          checksum: "f9563708ab117616eb7b07995108dfd730e152dec03d226bf17eec54a5eedf89",
        },
      ],
    },
  },
  {
    name: "FlClash",
    description: "基于 Clash.Meta 的开源多平台代理客户端，安卓端界面简洁，支持订阅、规则和多种代理协议。",
    url: "https://github.com/chen08209/FlClash/releases/",
    category: "network",
    categoryLabel: "网络工具",
    productType: "Android 代理客户端",
    coreVersion: "Clash.Meta / Mihomo",
    iconUrl: "assets/icons/flclash.png",
    initials: "FC",
    color: "linear-gradient(135deg, #6366f1, #3b82f6)",
    downloadInfo: {
      version: "0.8.96",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/flclash-v0.8.96",
      upstreamUrl: "https://github.com/chen08209/FlClash/releases/tag/v0.8.96",
      note: "下载 ZIP 后解压。Windows x64 适合常见 Intel / AMD 电脑；Android ARM64 适合大多数近年安卓手机。",
      files: [
        {
          label: "Windows x64",
          platform: "Windows",
          architecture: "x64（Intel / AMD）",
          format: "ZIP（内含 EXE 与许可证）",
          size: "35.55 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/007a5de8-363d-4d7c-97f8-3170ced4b047/FlClash-0.8.96-windows-amd64-setup.exe.zip",
          checksum: "9542e48660d75c8f625e10061b37a35664aac48c85ea741a45b04c0cf087cda5",
        },
        {
          label: "Android ARM64",
          platform: "Android",
          architecture: "ARM64（arm64-v8a）",
          format: "ZIP（内含 APK 与许可证）",
          size: "50.61 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/75e2c449-5c43-45bd-a471-892114d01ed4/FlClash-0.8.96-android-arm64-v8a.apk.zip",
          checksum: "c58606f398125bc70d866716550ae89e980ae5a838ccdd7c82ca822496aa4870",
        },
      ],
    },
  },
  {
    name: "v2rayNG",
    description: "基于 Xray-core 的开源 Android 代理客户端，适合 VLESS、VMess、Trojan 和 Shadowsocks 配置。",
    url: "https://github.com/2dust/v2rayNG/releases/",
    category: "network",
    categoryLabel: "网络工具",
    productType: "Android 代理客户端",
    coreVersion: "Xray-core",
    iconUrl: "assets/icons/v2rayng.png",
    initials: "V2",
    color: "linear-gradient(135deg, #111827, #4b5563)",
    downloadInfo: {
      version: "2.3.5（预发布）",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/v2rayng-2.3.5",
      upstreamUrl: "https://github.com/2dust/v2rayNG/releases/tag/2.3.5",
      note: "上游将 2.3.5 标记为预发布。下载 ZIP 后解压，当前提供 F-Droid 构建的 Android ARM64 版本。",
      files: [
        {
          label: "Android ARM64（F-Droid）",
          platform: "Android",
          architecture: "ARM64（arm64-v8a）",
          format: "ZIP（内含 APK 与许可证）",
          size: "30.19 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/3a000c6f-d7fb-4e79-9b34-12be924c1434/v2rayNG_2.3.5-fdroid_arm64-v8a.apk.zip",
          checksum: "f5e7b124f639527f79ff833a10720682a8d4011a1dea56345a2d1d9e0c550af5",
        },
      ],
    },
  },
  {
    name: "Hiddify",
    description: "开源跨平台代理客户端，官方 Release 提供 Android、Windows、macOS 和 Linux 版本。",
    url: "https://github.com/hiddify/hiddify-app/releases/",
    category: "network",
    categoryLabel: "网络工具",
    productType: "跨平台代理客户端",
    iconUrl: "assets/icons/hiddify.png",
    initials: "Hi",
    color: "linear-gradient(135deg, #3157e6, #6d8cff)",
  },
  {
    name: "sing-box for Android",
    description: "sing-box 官方 Android 客户端，可管理本地或远程配置，并通过 TUN 提供系统代理。",
    url: "https://sing-box.sagernet.org/clients/android/",
    category: "network",
    categoryLabel: "网络工具",
    productType: "Android 代理客户端",
    coreVersion: "sing-box",
    iconUrl: "assets/icons/sing-box.svg",
    initials: "SB",
    color: "linear-gradient(135deg, #1f2937, #64748b)",
    downloadInfo: {
      version: "1.13.19",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/sing-box-1.13.19",
      upstreamUrl: "https://github.com/SagerNet/sing-box/releases/tag/v1.13.19",
      note: "官方未修改安装包镜像，与 SagerNet 项目无隶属或合作关系。下载 ZIP 后解压。",
      files: [
        {
          label: "Android ARM64",
          platform: "Android",
          architecture: "ARM64（arm64-v8a）",
          format: "ZIP（内含 APK 与许可证）",
          size: "25.31 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/123f2d0a-1b71-4231-a264-5bc4d4342a4d/SFA-1.13.19-arm64-v8a.apk.zip",
          checksum: "53f19b2ef4769e16b1d0cd514318cd5023f9506477dfef3c28324688ab35b289",
        },
      ],
    },
  },
  {
    name: "Clash Meta for Android",
    description: "Clash.Meta 的开源 Android 图形客户端，支持规则分流、订阅导入和多种处理器架构。",
    url: "https://github.com/MetaCubeX/ClashMetaForAndroid/releases/",
    category: "network",
    categoryLabel: "网络工具",
    productType: "Android 代理客户端",
    coreVersion: "Clash.Meta / Mihomo",
    iconUrl: "assets/icons/clash-meta-for-android.png",
    initials: "CM",
    color: "linear-gradient(135deg, #1e3a5f, #3b82f6)",
    downloadInfo: {
      version: "2.11.33",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/cmfa-v2.11.33",
      upstreamUrl: "https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/v2.11.33",
      note: "下载 ZIP 后解压，当前提供 Android ARM64 版本。",
      files: [
        {
          label: "Android ARM64",
          platform: "Android",
          architecture: "ARM64（arm64-v8a）",
          format: "ZIP（内含 APK 与许可证）",
          size: "40.93 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/58813f2d-5d16-442d-a250-c746ae6e34b8/cmfa-2.11.33-meta-arm64-v8a-release.apk.zip",
          checksum: "3e8abb179c04ebaa45d6bec6efe21898654fcb66ebe7519a948d1743fc6e2566",
        },
      ],
    },
  },
  {
    name: "DeepSeek",
    description: "深度求索推出的通用对话、推理和代码助手。",
    strength: "中文推理、数学和代码性价比高，开放生态活跃，适合技术问答和复杂分析。",
    weakness: "高峰期稳定性可能波动，部分联网、文件和多模态体验不如头部综合助手完整。",
    url: "https://chat.deepseek.com/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "通用助手",
    recommendationRank: 4,
    bestFor: "适合：中文推理、数学、代码与技术问答",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "DS",
    color: "linear-gradient(135deg, #101828, #4b5563)",
    pinned: true,
  },
  {
    name: "Kimi",
    description: "月之暗面推出的长文本阅读、搜索和办公型 AI 助手。",
    strength: "长文档处理和资料总结能力突出，适合论文、报告、网页和文件阅读。",
    weakness: "部分功能需要登录或消耗额度，长任务和生成文件仍需人工检查。",
    url: "https://www.kimi.com/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "通用助手",
    recommendationRank: 1,
    bestFor: "适合：长文档、资料研究和复杂中文任务",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Ki",
    color: "linear-gradient(135deg, #0f766e, #22c55e)",
    pinned: true,
  },
  {
    name: "豆包",
    description: "字节跳动推出的综合 AI 助手，覆盖对话、写作、图片和日常办公。",
    strength: "中文日常使用体验好，功能入口多，适合写作、学习、图片生成和轻办公。",
    weakness: "不同客户端的功能可能有差异，专业结论和生成内容仍需核验。",
    url: "https://www.doubao.com/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "通用助手",
    recommendationRank: 6,
    bestFor: "适合：日常问答、写作、学习和多模态创作",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "DB",
    color: "linear-gradient(135deg, #2563eb, #7c3aed)",
  },
  {
    name: "千问",
    description: "阿里旗下全能 AI 助手，基于 Qwen 系列模型能力。",
    strength: "中文理解、办公写作和模型开放生态强，适合企业、开发者和通用问答。",
    weakness: "不同入口能力差异较大，部分专业能力需要切换到阿里云或开发者平台。",
    url: "https://www.qianwen.com/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "通用助手",
    recommendationRank: 2,
    bestFor: "适合：中文办公、通用问答和开发者生态",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["通义千问", "Qwen"],
    initials: "QW",
    color: "linear-gradient(135deg, #ef4444, #f97316)",
  },
  {
    name: "文心",
    description: "百度文心大模型入口，覆盖搜索、创作和多模态能力。",
    strength: "与百度搜索和中文内容生态结合紧密，适合中文检索、问答和内容生成。",
    weakness: "产品命名和入口变更较多，复杂推理和代码场景通常不是首选。",
    url: "https://wenxin.baidu.com/",
    iconUrl: "assets/icons/wenxin.png",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "通用助手",
    recommendationRank: 5,
    bestFor: "适合：百度生态检索、中文问答和内容生成",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["文心一言", "ERNIE"],
    initials: "WX",
    color: "linear-gradient(135deg, #1d4ed8, #38bdf8)",
  },
  {
    name: "腾讯元宝",
    description: "腾讯推出的 AI 助手，面向搜索、阅读、写作和创作。",
    strength: "中文资料阅读、公众号/腾讯生态内容结合较好，适合日常搜索和文档理解。",
    weakness: "国际模型生态和开放开发能力相对有限，部分能力受平台入口影响。",
    url: "https://yuanbao.tencent.com/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "通用助手",
    recommendationRank: 7,
    bestFor: "适合：公众号资料、腾讯生态和文档阅读",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "YB",
    color: "linear-gradient(135deg, #0ea5e9, #2563eb)",
  },
  {
    name: "讯飞星火",
    description: "科大讯飞推出的 AI 助手，侧重语音、教育和办公场景。",
    strength: "语音识别、语音交互和教育类应用积累深，适合语音转写、学习和办公生成。",
    weakness: "通用编程和开放生态不如开发者型平台，部分功能更偏垂直场景。",
    url: "https://xinghuo.xfyun.cn/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "教育语音",
    recommendationRank: 1,
    bestFor: "适合：语音转写、教育学习和办公生成",
    rankingNote: "按教育语音用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "XH",
    color: "linear-gradient(135deg, #dc2626, #f59e0b)",
  },
  {
    name: "智谱清言",
    description: "智谱推出的中文 AI 助手，提供问答、内容创作与资料处理。",
    strength: "中文问答、知识处理和多模态能力均衡，背后有较强开源模型生态。",
    weakness: "产品体验和高级功能稳定性需按实际入口确认，海外生态影响力较有限。",
    url: "https://chatglm.cn/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "通用助手",
    recommendationRank: 3,
    bestFor: "适合：中文知识任务、多模态和开源模型用户",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["GLM", "ChatGLM"],
    initials: "GLM",
    color: "linear-gradient(135deg, #7c3aed, #ec4899)",
  },
  {
    name: "秘塔 AI 搜索",
    description: "面向检索、资料整理和报告生成的 AI 搜索工具。",
    strength: "搜索结果组织清晰，适合快速查资料、核验来源和生成调研提纲。",
    weakness: "生成式创作和复杂多轮推理不是核心优势，搜索结果仍需人工核验。",
    url: "https://metaso.cn/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "搜索研究",
    recommendationRank: 2,
    bestFor: "适合：中文检索、来源核验和调研提纲",
    rankingNote: "按搜索研究用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "MT",
    color: "linear-gradient(135deg, #059669, #14b8a6)",
  },
  {
    name: "夸克",
    description: "阿里旗下 AI 搜索、浏览器、网盘和文档工具一体化入口。",
    strength: "国内访问方便，搜索、网页阅读、PDF、网盘和多端协同集中在一个产品中。",
    weakness: "功能较多且部分体验依赖客户端，专业深度研究仍需交叉核验来源。",
    url: "https://www.quark.cn/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "搜索研究",
    recommendationRank: 1,
    bestFor: "适合：日常搜索、网页阅读、PDF 和资料管理",
    rankingNote: "按搜索研究用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["Quark", "夸克 AI"],
    initials: "QK",
    color: "linear-gradient(135deg, #f97316, #2563eb)",
  },
  {
    name: "可灵 AI",
    description: "快手推出的 AI 视频与图片生成平台。",
    strength: "视频生成质量和中文提示理解较强，适合短视频、分镜和创意影像制作。",
    weakness: "高质量生成通常消耗额度，长视频一致性和精细控制仍需反复调参。",
    url: "https://klingai.kuaishou.com/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "图像视频",
    recommendationRank: 3,
    bestFor: "适合：短视频、分镜和高质量图生视频",
    rankingNote: "按图像视频用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "KL",
    color: "linear-gradient(135deg, #f97316, #db2777)",
  },
  {
    name: "即梦 AI",
    description: "剪映体系下的 AI 图片、视频和智能画布工具。",
    strength: "中文创作链路顺手，适合图生视频、短视频素材和社媒视觉内容。",
    weakness: "更偏内容创作场景，复杂工业级视频控制和开放 API 能力有限。",
    url: "https://jimeng.jianying.com/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "图像视频",
    recommendationRank: 1,
    bestFor: "适合：中文图像、视频素材和剪映创作链路",
    rankingNote: "按图像视频用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["Dreamina", "Seedance"],
    initials: "JM",
    color: "linear-gradient(135deg, #111827, #f43f5e)",
  },
  {
    name: "海螺 AI",
    description: "MiniMax 旗下的 AI 视频创作平台，支持文字与图像驱动的视频生成。",
    strength: "视频生成和多模态创作能力强，适合创意短片、图像动效和视觉内容生产。",
    weakness: "生成结果稳定性受提示词和额度影响，专业剪辑仍需要后期工具配合。",
    url: "https://hailuoai.video/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "图像视频",
    recommendationRank: 2,
    bestFor: "适合：创意短片、图像动效和多模态素材",
    rankingNote: "按图像视频用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "HL",
    color: "linear-gradient(135deg, #0f172a, #06b6d4)",
  },
  {
    name: "Trae",
    iconUrl: "assets/icons/trae.png",
    description: "TRAE 的 AI 编程入口，当前提供 TraeCode，并另有 TraeWork 办公产品。",
    strength: "兼顾传统编辑器操作和 Agent 式开发，适合中文用户进行项目级编码。",
    weakness: "复杂工程改动仍需人工审查和测试，部分高级能力受版本与账号限制。",
    url: "https://www.trae.cn/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "AI IDE",
    recommendationRank: 1,
    bestFor: "适合：中文环境下的项目开发和 Agent 式编码",
    rankingNote: "官网当前区分 TraeCode 编程与 TraeWork 办公，按开发用途收录。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["TraeCode", "TRAE IDE", "TRAE SOLO"],
    initials: "Tr",
    color: "linear-gradient(135deg, #2563eb, #7c3aed)",
  },
  {
    name: "Reasonix",
    iconUrl: "assets/icons/reasonix.svg",
    description: "面向 DeepSeek 模型优化的终端编程 Agent。",
    strength: "可在终端中理解代码库、规划任务并执行多文件修改，DeepSeek 接入路径清晰。",
    weakness: "属于第三方工具且偏命令行工作流，使用前仍需核对权限、改动和测试结果。",
    url: "https://reasonix.io/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "编程 Agent",
    recommendationRank: 1,
    bestFor: "适合：DeepSeek 用户的终端代码任务",
    rankingNote: "按编程 Agent用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["DeepSeek Reasonix"],
    initials: "Rx",
    color: "linear-gradient(135deg, #0f172a, #2563eb)",
  },
  {
    name: "DeepSeek Harness",
    iconUrl: "assets/icons/deepseek-harness.svg",
    parentProduct: "DeepSeek",
    description: "DeepSeek 开源的本地优先 Coding Agent 与 Agent 开发运行环境。",
    strength: "通过插件组合工具、提示词和上下文，可切换模型并扩展自己的 Agent 工作流。",
    weakness: "当前为开发者预览，更适合愿意配置和调试工具链的开发者。",
    url: "https://www.deepseek.com/harness/",
    category: "china-ai",
    categoryLabel: "国内 AI",
    useCase: "Agent 框架",
    recommendationRank: 1,
    bestFor: "适合：本地搭建和扩展 Coding Agent",
    rankingNote: "按Agent 框架用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["DSH", "DeepSeek Agent Harness"],
    initials: "DSH",
    color: "linear-gradient(135deg, #111827, #10b981)",
  },
  {
    name: "ChatGPT",
    description: "OpenAI 推出的综合 AI 助手，覆盖对话、写作、代码、图像和研究。",
    strength: "综合能力和工具生态成熟，适合写作、编程、多模态分析和复杂任务协作。",
    weakness: "高级模型和高额度通常需要付费，实时信息和专业结论仍需核验。",
    url: "https://chatgpt.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "通用助手",
    recommendationRank: 2,
    bestFor: "适合：综合问答、写作、编程、图像和复杂任务",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "GPT",
    color: "linear-gradient(135deg, #111827, #10a37f)",
    pinned: true,
  },
  {
    name: "Claude",
    description: "Anthropic 推出的 AI 助手，擅长长文本、写作和代码协作。",
    strength: "长文档理解、英文写作、代码解释和安全边界表现稳定。",
    weakness: "部分地区访问和计费受限，图片/视频生成等创作能力不如专用工具。",
    url: "https://claude.ai/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "通用助手",
    recommendationRank: 1,
    bestFor: "适合：长文档、英文写作、代码和知识工作",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Cl",
    color: "linear-gradient(135deg, #3f2a1d, #c08457)",
  },
  {
    name: "Gemini",
    description: "Google 推出的多模态 AI 助手，与 Google 生态结合紧密。",
    strength: "搜索、长上下文、图片理解和 Google 应用生态整合有优势。",
    weakness: "不同地区可用功能差异明显，部分回答风格偏保守。",
    url: "https://gemini.google.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "通用助手",
    recommendationRank: 3,
    bestFor: "适合：搜索、多模态、长上下文和 Google 生态",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Ge",
    color: "linear-gradient(135deg, #4285f4, #a142f4)",
    pinned: true,
  },
  {
    name: "Perplexity",
    description: "以引用来源和联网检索为核心的 AI 搜索工具。",
    strength: "搜索型问答、引用来源和快速查资料体验好，适合调研和事实核验。",
    weakness: "引用来源不保证结论正确，深度研究和高级功能受套餐与额度影响。",
    url: "https://www.perplexity.ai/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "研究知识",
    recommendationRank: 2,
    bestFor: "适合：联网检索、快速调研和来源核验",
    rankingNote: "按研究知识用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Px",
    color: "linear-gradient(135deg, #0f766e, #111827)",
  },
  {
    name: "Gemini Notebook",
    parentProduct: "Gemini",
    description: "Google 的来源驱动研究与学习工具，原名 NotebookLM。",
    strength: "围绕用户资料生成摘要、问答和音频概览，回答能回到来源，研究链路清晰。",
    weakness: "依赖 Google 账号且部分地区访问受限，来源本身有误时结果仍需人工判断。",
    url: "https://notebook.google/",
    iconUrl: "assets/icons/notebooklm.google.png",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "研究知识",
    recommendationRank: 1,
    bestFor: "适合：论文、课程、报告和私有资料研究",
    rankingNote: "官网已使用 Gemini Notebook 名称，提供来源驱动的资料研究入口。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["NotebookLM", "谷歌笔记本"],
    initials: "GN",
    color: "linear-gradient(135deg, #4285f4, #34a853)",
  },
  {
    name: "Microsoft Copilot",
    description: "微软 AI 助手，整合 Bing、Edge、Windows 和 Microsoft 365。",
    strength: "办公生态整合强，适合 Office 文档、搜索和微软工作流。",
    weakness: "不同版本功能差异大，高级办公能力多依赖订阅和企业配置。",
    url: "https://copilot.microsoft.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "通用助手",
    recommendationRank: 6,
    bestFor: "适合：Windows、Edge 和 Microsoft 365 工作流",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Co",
    color: "linear-gradient(135deg, #2563eb, #22c55e)",
  },
  {
    name: "Grok",
    description: "xAI 推出的 AI 助手，与 X 平台信息流结合紧密。",
    strength: "热点信息、社交平台内容和较开放的对话风格是主要特色。",
    weakness: "实时信息与生成结果需要核验，功能及额度以账号和套餐为准。",
    url: "https://grok.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "通用助手",
    recommendationRank: 4,
    bestFor: "适合：热点追踪、X 平台信息和开放式对话",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Gk",
    color: "linear-gradient(135deg, #000000, #525252)",
  },
  {
    name: "Meta AI",
    description: "Meta 推出的通用 AI 助手，与其社交和创作生态结合。",
    strength: "通用问答、图片创作和 Meta 应用整合方便，移动端用户增长较快。",
    weakness: "中国大陆不可直接使用，地区、账号和产品入口限制明显。",
    url: "https://www.meta.ai/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "通用助手",
    recommendationRank: 5,
    bestFor: "适合：Meta 生态用户和轻量日常创作",
    rankingNote: "按通用助手用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Meta",
    color: "linear-gradient(135deg, #0668e1, #7c3aed)",
  },
  {
    name: "Poe",
    description: "Quora 推出的多模型聚合聊天平台。",
    strength: "一个入口体验多种模型和机器人，适合快速对比不同模型输出。",
    weakness: "核心能力取决于接入模型，额度、上下文和价格规则较复杂。",
    url: "https://poe.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "多模型平台",
    recommendationRank: 3,
    bestFor: "适合：一个入口对比多种模型和机器人",
    rankingNote: "按多模型平台用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Poe",
    color: "linear-gradient(135deg, #7c3aed, #2563eb)",
  },
  {
    name: "Genspark",
    description: "可完成研究、文档、表格、演示和多步骤任务的综合 AI Workspace。",
    strength: "聚合多种模型并能直接交付报告、PPT、表格和网页，任务覆盖面广。",
    weakness: "复杂任务消耗额度较快，聚合模型的效果和隐私边界需按具体工作流判断。",
    url: "https://www.genspark.ai/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "Agent",
    recommendationRank: 1,
    bestFor: "适合：调研、PPT、表格和跨工具任务",
    rankingNote: "按Agent用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "GS",
    color: "linear-gradient(135deg, #6d28d9, #06b6d4)",
  },
  {
    name: "Manus",
    description: "可自主执行研究、建站、演示和浏览器操作的通用 AI Agent。",
    strength: "能把开放式需求拆解为多步骤任务并交付成品，适合减少重复操作。",
    weakness: "高强度任务依赖额度和外部权限，处理敏感账号或文件前需谨慎授权。",
    url: "https://manus.im/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "Agent",
    recommendationRank: 2,
    bestFor: "适合：网站、演示、研究和浏览器自动化",
    rankingNote: "按Agent用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Ma",
    color: "linear-gradient(135deg, #111827, #4f46e5)",
  },
  {
    name: "Hugging Face",
    description: "全球模型、数据集和开源 AI 应用社区。",
    strength: "开源模型资源最丰富之一，适合找模型、数据集、Demo 和开发资料。",
    weakness: "更偏开发者和研究者，普通用户直接上手门槛较高。",
    url: "https://huggingface.co/",
    category: "dev",
    categoryLabel: "开发工具",
    initials: "HF",
    color: "linear-gradient(135deg, #fbbf24, #fb923c)",
  },
  {
    name: "Midjourney",
    description: "高质量 AI 图像与视觉创作平台。",
    strength: "审美、风格化和成片质感突出，适合海报、概念图和创意视觉。",
    weakness: "精确文字、严格可控编辑和商业流程管理不如设计/修图专用工具。",
    url: "https://www.midjourney.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "图像设计",
    recommendationRank: 1,
    bestFor: "适合：海报、概念图和高审美风格化视觉",
    rankingNote: "按图像设计用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "MJ",
    color: "linear-gradient(135deg, #111827, #8b5cf6)",
  },
  {
    name: "Runway",
    description: "面向影视和创意行业的 AI 视频生成与编辑平台。",
    strength: "视频生成、视频编辑和创意工作流成熟，适合短片、广告和动态视觉。",
    weakness: "费用较高，长镜头一致性和精细物理控制仍需要多次生成。",
    url: "https://runway.com/",
    iconUrl: "assets/icons/runwayml.com.png",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "视频创作",
    recommendationRank: 1,
    bestFor: "适合：短片、广告和 AI 视频编辑工作流",
    rankingNote: "按视频创作用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "RW",
    color: "linear-gradient(135deg, #171717, #737373)",
  },
  {
    name: "Higgsfield",
    description: "面向广告、社媒和电影感镜头的 AI 视频创作平台。",
    strength: "镜头运动、人物表现和短视频模板丰富，适合快速制作视觉冲击力强的内容。",
    weakness: "高级模型和高质量输出成本较高，复杂长片仍需要剪辑与一致性控制。",
    url: "https://higgsfield.ai/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "视频创作",
    recommendationRank: 2,
    bestFor: "适合：广告镜头、人物短片和社媒视频",
    rankingNote: "按视频创作用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Hi",
    color: "linear-gradient(135deg, #111827, #ec4899)",
  },
  {
    name: "Canva AI",
    description: "Canva 里的 AI 设计、写作、图片和视频工具集合。",
    strength: "模板、排版和团队协作强，适合非设计师快速做海报、PPT 和社媒素材。",
    weakness: "高级视觉控制和专业设计细节不如 Photoshop、Figma 等专业工具。",
    url: "https://www.canva.com/canva-ai/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "图像设计",
    recommendationRank: 2,
    bestFor: "适合：非设计师制作海报、PPT 和社媒素材",
    rankingNote: "按图像设计用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Ca",
    color: "linear-gradient(135deg, #00c4cc, #7d2ae8)",
  },
  {
    name: "ElevenLabs",
    description: "AI 语音生成、配音、克隆和语音 Agent 平台。",
    strength: "语音自然度、配音质量和多语言声音生成能力强。",
    weakness: "高质量和商用场景成本较高，声音版权和授权需要特别注意。",
    url: "https://elevenlabs.io/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "语音",
    recommendationRank: 1,
    bestFor: "适合：多语言配音、声音克隆和语音 Agent",
    rankingNote: "按语音用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "11",
    color: "linear-gradient(135deg, #111827, #64748b)",
  },
  {
    name: "Suno",
    description: "AI 音乐生成平台，可根据提示词生成歌曲和伴奏。",
    strength: "可从歌词生成歌曲，适合 Demo、短视频配乐、旋律草稿和灵感记录。",
    weakness: "2026-09-03 起下载受套餐限制：Pro 每月 20 次、Premier 每月 60 次；Premier 使用 Studio 有例外，详见官方政策。",
    url: "https://suno.com/",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "歌曲生成",
    recommendationRank: 1,
    bestFor: "适合：歌曲创作、Demo 和短视频配乐",
    rankingNote: "提供歌曲生成与 Studio 编辑；下载次数和适用例外见官方政策。",
    sourceIds: ["official","sunoStudio","sunoDownloads"],
    verifiedAt: "2026-09-05",
    initials: "Su",
    color: "linear-gradient(135deg, #f97316, #7c2d12)",
  },
  {
    name: "Udio",
    description: "面向歌曲生成、歌词创作和音频延展的 AI 音乐平台。",
    strength: "可探索人声和音乐风格，适合生成歌曲片段、延展歌曲和记录灵感。",
    weakness: "当前不能下载音频、视频或分轨，平台正处于授权合作后的产品过渡期。",
    url: "https://www.udio.com/",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "歌曲生成",
    recommendationRank: 3,
    bestFor: "适合：人声、风格实验和歌曲片段迭代",
    rankingNote: "官方帮助中心仍注明音频、视频和分轨下载已禁用；适合站内创作与试听。",
    sourceIds: ["official","udioLimits"],
    verifiedAt: "2026-09-05",
    initials: "Ud",
    color: "linear-gradient(135deg, #111827, #7c3aed)",
  },
  {
    name: "Stable Audio",
    description: "Stability AI 推出的生成式音乐和音效平台。",
    strength: "适合生成配乐、氛围音、音效和音乐素材，偏素材生产和声音设计。",
    weakness: "歌曲生成和中文歌词场景不一定是强项，额度和授权以官网为准。",
    url: "https://stableaudio.com/",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "配乐素材",
    recommendationRank: 1,
    bestFor: "适合：器乐配乐、氛围音和声音设计",
    rankingNote: "按配乐素材用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "SA",
    color: "linear-gradient(135deg, #0f172a, #8b5cf6)",
  },
  {
    name: "ElevenLabs Music",
    parentProduct: "ElevenLabs",
    moduleLabel: "音乐生成",
    description: "ElevenLabs 的 AI 音乐生成工具，可用自然语言生成歌曲和纯音乐。",
    strength: "音频生成体系成熟，适合生成带人声或纯音乐的高质感音乐草稿。",
    weakness: "音乐版权、禁止模仿对象和商用范围需要严格按 ElevenLabs Music Terms 核验。",
    url: "https://elevenlabs.io/music",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "歌曲生成",
    recommendationRank: 2,
    bestFor: "适合：品牌、商用内容和多语言歌曲草稿",
    rankingNote: "按歌曲生成用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "11",
    color: "linear-gradient(135deg, #111827, #64748b)",
  },
  {
    name: "AIVA",
    description: "AI 音乐生成助手，偏配乐、古典、管弦和影视游戏音乐。",
    strength: "可生成多种风格的器乐配乐，支持 MIDI/音频工作流，适合背景音乐和编曲草稿。",
    weakness: "流行歌人声生成不是核心强项，免费和低阶套餐的商用限制较多。",
    url: "https://www.aiva.ai/",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "配乐素材",
    recommendationRank: 3,
    bestFor: "适合：古典、管弦、影视和游戏配乐",
    rankingNote: "按配乐素材用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "AI",
    color: "linear-gradient(135deg, #1e3a8a, #38bdf8)",
  },
  {
    name: "SOUNDRAW",
    description: "面向创作者的 AI 免版税背景音乐生成平台。",
    strength: "适合快速生成可编辑的 BGM、视频配乐和社媒内容音乐。",
    weakness: "更偏背景音乐，复杂歌曲结构、人声和高度个性化编曲能力有限。",
    url: "https://soundraw.io/",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "配乐素材",
    recommendationRank: 2,
    bestFor: "适合：视频、播客和社媒免版税 BGM",
    rankingNote: "按配乐素材用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "SR",
    color: "linear-gradient(135deg, #06b6d4, #22c55e)",
  },
  {
    name: "Mubert",
    description: "AI 音乐生成平台，可按提示词、场景、情绪和用途生成音乐。",
    strength: "适合视频、播客、游戏和直播背景音乐，生成速度快，场景化明显。",
    weakness: "以背景音乐为主，独立发行、广告和商业项目需核对相应授权。",
    url: "https://mubert.ai/",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "配乐素材",
    recommendationRank: 4,
    bestFor: "适合：直播、播客、游戏和场景化背景音乐",
    rankingNote: "按配乐素材用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Mu",
    color: "linear-gradient(135deg, #7c3aed, #ec4899)",
  },
  {
    name: "Gemini 音乐（Lyria）",
    parentProduct: "Gemini",
    moduleLabel: "音乐生成",
    description: "Google Gemini 内置的 Lyria 音乐生成入口，可由文字或图片创建音乐片段。",
    strength: "与 Gemini 多模态入口结合，提示方式简单，并重视来源标记和版权合作。",
    weakness: "生成长度、地区和账号可用性受限，不适合需要完整 DAW 控制的专业制作。",
    url: "https://gemini.google.com/",
    category: "music-ai",
    categoryLabel: "音乐 AI",
    useCase: "音乐片段",
    recommendationRank: 1,
    bestFor: "适合：Gemini 用户快速生成短音乐片段",
    rankingNote: "按音乐片段用途收录；可用模型、时长和功能以 Gemini 账号为准。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["MusicFX", "Lyria", "Google 音乐"],
    initials: "Ly",
    color: "linear-gradient(135deg, #4285f4, #34a853)",
  },
  {
    name: "Cursor",
    description: "面向程序员的 AI 代码编辑器。",
    strength: "代码补全、项目级问答和代码修改体验强，适合真实工程开发。",
    weakness: "需要本地开发基础和项目上下文，复杂改动仍要人工审查和测试。",
    url: "https://cursor.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "AI IDE",
    recommendationRank: 1,
    bestFor: "适合：真实代码项目、补全和项目级修改",
    rankingNote: "按AI IDE用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Cu",
    color: "linear-gradient(135deg, #111827, #2563eb)",
  },
  {
    name: "Codex",
    iconUrl: "assets/icons/codex.png",
    parentProduct: "ChatGPT",
    description: "OpenAI 推出的 Coding Agent，可在应用、IDE、终端和云端协作编程。",
    strength: "能读取代码库、修改文件、运行命令并处理较完整的软件开发任务。",
    weakness: "涉及生产系统、敏感权限和高风险改动时仍需人工审查与验证。",
    url: "https://openai.com/codex/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "编程 Agent",
    recommendationRank: 1,
    bestFor: "适合：跨 IDE、终端和云端完成工程任务",
    rankingNote: "按编程 Agent用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["OpenAI Codex", "Codex CLI"],
    initials: "Cd",
    color: "linear-gradient(135deg, #111827, #10a37f)",
  },
  {
    name: "Claude Code",
    iconUrl: "assets/icons/claude-code.png",
    parentProduct: "Claude",
    description: "Anthropic 推出的 Coding Agent，可在终端、IDE、桌面和 Web 中使用。",
    strength: "擅长理解代码库、执行多步骤修改和配合现有开发工具链。",
    weakness: "实际效果依赖模型额度、项目上下文和权限配置，生成改动仍需审查。",
    url: "https://claude.com/product/claude-code",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "编程 Agent",
    recommendationRank: 2,
    bestFor: "适合：终端和 IDE 中的复杂代码协作",
    rankingNote: "按编程 Agent用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["Claude CLI"],
    initials: "CC",
    color: "linear-gradient(135deg, #d97757, #7c2d12)",
  },
  {
    name: "OpenCode",
    iconUrl: "assets/icons/opencode.png",
    description: "开源 Coding Agent，支持终端、IDE 和桌面端，并可连接多种模型。",
    strength: "模型与提供商选择灵活，适合希望使用开放工具链的开发者。",
    weakness: "不同模型和配置的体验差异较大，需要自行管理密钥、权限和运行环境。",
    url: "https://opencode.ai/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "编程 Agent",
    recommendationRank: 3,
    bestFor: "适合：多模型、开源和可定制的编程工作流",
    rankingNote: "按编程 Agent用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    aliases: ["Open Code"],
    initials: "OC",
    color: "linear-gradient(135deg, #111827, #64748b)",
    downloadInfo: {
      version: "1.18.25",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/opencode-1.18.25",
      upstreamUrl: "https://github.com/anomalyco/opencode/releases/tag/v1.18.25",
      note: "官方 CLI 二进制，ZIP 内附 MIT 许可证。Windows x64 适合常见 Intel / AMD 电脑；macOS ARM64 适合 Apple 芯片 Mac。",
      files: [
        {
          label: "Windows x64",
          platform: "Windows",
          architecture: "x64（Intel / AMD）",
          format: "ZIP（内含 EXE 与许可证）",
          size: "57.36 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/5592ac0a-9aa9-4dc3-9e91-4b582b360468/OpenCode-1.18.25-windows-x64.zip",
          checksum: "d743c6b296557638c428257cef0b244481571f83d1c456723135c064c979bf0d",
        },
        {
          label: "macOS Apple 芯片",
          platform: "macOS",
          architecture: "ARM64（Apple M 系列）",
          format: "ZIP（内含可执行文件与许可证）",
          size: "43.93 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/7ade9fed-91cf-43ab-a8f9-5b941f19e86c/OpenCode-1.18.25-macos-arm64.zip",
          checksum: "ff4fdb41dfc214bd4ea7c8c59a1ebecdc0cfa95d380f4e85428445ced9888299",
        },
      ],
    },
  },
  {
    name: "Replit",
    description: "云端开发环境和 AI Agent 建站/编程平台。",
    strength: "浏览器内即可从提示词生成、运行和发布应用，适合原型和轻量项目。",
    weakness: "复杂生产工程、性能调优和架构治理仍需要开发经验。",
    url: "https://replit.com/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "编程建站",
    recommendationRank: 2,
    bestFor: "适合：浏览器内生成、运行和发布轻量应用",
    rankingNote: "按编程建站用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Re",
    color: "linear-gradient(135deg, #f97316, #111827)",
  },
  {
    name: "Lovable",
    description: "通过自然语言生成和迭代 Web 应用的 AI 建站平台。",
    strength: "从需求到可运行前端速度快，适合无代码原型、落地页和小型产品验证。",
    weakness: "复杂后端、安全和长期维护仍需要开发经验，生成代码必须人工审查。",
    url: "https://lovable.dev/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "编程建站",
    recommendationRank: 3,
    bestFor: "适合：无代码原型、落地页和轻量 Web 应用",
    rankingNote: "按编程建站用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Lo",
    color: "linear-gradient(135deg, #f43f5e, #7c3aed)",
  },
  {
    name: "Gamma",
    description: "AI 演示文稿、网页和文档生成工具。",
    strength: "PPT/网页初稿生成快，版式统一，适合汇报、课程和轻量展示。",
    weakness: "深度定制和复杂品牌规范不如专业设计工具，内容仍需人工校对。",
    url: "https://gamma.app/",
    category: "global-ai",
    categoryLabel: "国外 AI",
    useCase: "办公展示",
    recommendationRank: 1,
    bestFor: "适合：快速生成 PPT、文档和轻量网页",
    rankingNote: "按办公展示用途收录；功能以产品官网为准，展示顺序不代表模型榜单名次。",
    sourceIds: ["official"],
    verifiedAt: "2026-09-05",
    initials: "Ga",
    color: "linear-gradient(135deg, #6d28d9, #f97316)",
  },
  {
    name: "Visual Studio Code",
    description: "微软官方代码编辑器下载。",
    url: "https://code.visualstudio.com/",
    category: "dev",
    categoryLabel: "开发工具",
    initials: "VS",
    color: "linear-gradient(135deg, #0066b8, #23a9f2)",
  },
  {
    name: "GitHub",
    description: "代码托管、协作开发和开源项目平台。",
    url: "https://github.com/",
    category: "dev",
    categoryLabel: "开发工具",
    initials: "GH",
    color: "linear-gradient(135deg, #24292f, #57606a)",
  },
  {
    name: "Python",
    description: "Python 官方下载、文档和包索引入口。",
    url: "https://www.python.org/",
    category: "dev",
    categoryLabel: "开发工具",
    initials: "Py",
    color: "linear-gradient(135deg, #306998, #ffd43b)",
    downloadInfo: {
      version: "3.14.7",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/python-3.14.7",
      upstreamUrl: "https://www.python.org/downloads/release/python-3147/",
      note: "下载 ZIP 后解压并运行官方 Windows 安装程序；ZIP 内附 PSF 许可证。",
      files: [
        {
          label: "Windows x64",
          platform: "Windows",
          architecture: "x64（Intel / AMD）",
          format: "ZIP（内含 EXE 与许可证）",
          size: "31.73 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/1074aeb6-fb15-43cf-8314-dfdbd25f8d6b/Python-3.14.7-windows-x64.zip",
          checksum: "8919c882619e27bd45d2ea1a8f9252adc444c3eec40ec7633d26df48638bda86",
        },
      ],
    },
  },
  {
    name: "Node.js",
    description: "Node.js 官方运行时下载与文档。",
    url: "https://nodejs.org/",
    category: "dev",
    categoryLabel: "开发工具",
    initials: "JS",
    color: "linear-gradient(135deg, #3c873a, #68a063)",
    downloadInfo: {
      version: "24.20.0 LTS",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/nodejs-24.20.0",
      upstreamUrl: "https://nodejs.org/dist/v24.20.0/",
      note: "官方 Node.js 24 LTS 安装包，ZIP 内附 MIT 许可证。Windows 包含 MSI；macOS 包含 ARM64 TAR.GZ。",
      files: [
        {
          label: "Windows x64",
          platform: "Windows",
          architecture: "x64（Intel / AMD）",
          format: "ZIP（内含 MSI 与许可证）",
          size: "31.79 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/0a39110a-bf43-4abd-a0d2-04469925a8ee/Node.js-24.20.0-windows-x64.zip",
          checksum: "63416865e24cdcb0b7d70539ffe504ffdae83bafd97572111bc3db4165873f34",
        },
        {
          label: "macOS Apple 芯片",
          platform: "macOS",
          architecture: "ARM64（Apple M 系列）",
          format: "ZIP（内含 TAR.GZ 与许可证）",
          size: "50.52 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/b91fc0d0-a483-4cdf-a46c-5dc05938677b/Node.js-24.20.0-macos-arm64.zip",
          checksum: "54a31ce7ce805a54958ec9f18ac28c58e3be49b64885268297207df0487853a7",
        },
      ],
    },
  },
  {
    name: "Docker",
    description: "Docker 官方容器平台与 Desktop 下载。",
    url: "https://www.docker.com/",
    category: "dev",
    categoryLabel: "开发工具",
    initials: "Do",
    color: "linear-gradient(135deg, #0db7ed, #2496ed)",
  },
  {
    name: "图吧工具箱",
    description: "面向 Windows 的硬件检测、性能测试和系统维护工具合集。",
    url: "https://www.tbtool.cn/",
    category: "dev",
    categoryLabel: "开发工具",
    initials: "图吧",
    color: "linear-gradient(135deg, #2563eb, #0f172a)",
  },
  {
    name: "Git",
    description: "分布式版本控制系统，AI 编程工具读写代码仓库、查看差异和协作提交时常用。",
    url: "https://git-scm.com/downloads",
    category: "ai-dependency",
    categoryLabel: "AI 依赖",
    initials: "Git",
    color: "linear-gradient(135deg, #f05032, #111827)",
    downloadInfo: {
      version: "2.55.0.5",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/git-2.55.0.5",
      upstreamUrl: "https://github.com/git-for-windows/git/releases/tag/v2.55.0.windows.5",
      note: "Git for Windows 官方安装程序，下载 ZIP 后解压；ZIP 内附 GPLv2 许可证。",
      files: [
        {
          label: "Windows x64",
          platform: "Windows",
          architecture: "x64（Intel / AMD）",
          format: "ZIP（内含 EXE 与许可证）",
          size: "62.33 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/files/TY6g7miU68tmAChpUZvrfF/f9c985ee-83e3-4f67-99c1-14e0a14e07f6/Git-2.55.0.5-windows-x64.zip",
          checksum: "572911ffaa845bfa6e836d2017f8951cdb503ed8a40ca5eb7f7d820797090ff9",
        },
      ],
    },
  },
  {
    name: "WSL2",
    iconUrl: "assets/icons/wsl.png",
    description: "Windows 上运行 Linux 开发环境，适合 Codex、Claude Code 和常见命令行开发工具。",
    url: "https://learn.microsoft.com/windows/wsl/install",
    category: "ai-dependency",
    categoryLabel: "AI 依赖",
    initials: "WSL",
    color: "linear-gradient(135deg, #0078d4, #1f2937)",
  },
  {
    name: "Ubuntu for WSL",
    description: "WSL 中常用的 Ubuntu Linux 环境，适合搭建 Node.js、Python、Git 和 AI 编程工具链。",
    url: "https://ubuntu.com/desktop/wsl",
    category: "ai-dependency",
    categoryLabel: "AI 依赖",
    initials: "Ub",
    color: "linear-gradient(135deg, #e95420, #77216f)",
  },
  {
    name: "ripgrep / rg",
    iconUrl: "",
    description: "高速代码搜索工具，常被 AI 编程 Agent 用于快速检索项目文件和定位上下文。",
    url: "https://github.com/BurntSushi/ripgrep/releases",
    category: "ai-dependency",
    categoryLabel: "AI 依赖",
    initials: "rg",
    color: "linear-gradient(135deg, #111827, #f59e0b)",
    downloadInfo: {
      version: "15.2.0",
      releaseUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/tag/ripgrep-15.2.0",
      upstreamUrl: "https://github.com/BurntSushi/ripgrep/releases/tag/15.2.0",
      note: "Windows 便携版，解压后运行 rg.exe。当前已上传 x64 版本。",
      files: [
        {
          label: "Windows x64",
          platform: "Windows",
          architecture: "x64（Intel / AMD）",
          format: "ZIP",
          size: "1.71 MiB",
          url: "https://cnb.cool/kaoyawei/downloads/-/releases/download/ripgrep-15.2.0/ripgrep-15.2.0-x86_64-pc-windows-msvc.zip",
          checksum: "71b2fef860abe467217a538ff31de02f5258807c0129f771846f87bd029aafc5",
          checksumUrl: "https://cnb.cool/kaoyawei/downloads/-/releases/download/ripgrep-15.2.0/ripgrep-15.2.0-x86_64-pc-windows-msvc.zip.sha256",
        },
      ],
    },
  },
  {
    name: "百度网盘",
    description: "百度网盘官方客户端下载入口，支持 Windows、Mac、移动端等常用平台。",
    url: "https://pan.baidu.com/download",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "BD",
    color: "linear-gradient(135deg, #2563eb, #60a5fa)",
    pinned: true,
  },
  {
    name: "阿里云盘",
    description: "阿里云盘官方入口，提供个人云存储、文件管理、同步与分享服务。",
    url: "https://www.aliyundrive.com/",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "AL",
    color: "linear-gradient(135deg, #ff6a00, #2563eb)",
    pinned: true,
  },
  {
    name: "夸克网盘",
    description: "夸克网盘网页版和客户端下载入口，覆盖 Windows、macOS、移动端等平台。",
    url: "https://pan.quark.cn/",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "QK",
    color: "linear-gradient(135deg, #111827, #00a3ff)",
    pinned: true,
  },
  {
    name: "腾讯微云",
    description: "腾讯微云官方下载入口，支持文件备份、同步、查看和分享。",
    url: "https://www.weiyun.com/download.html",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "WY",
    color: "linear-gradient(135deg, #0ea5e9, #22c55e)",
  },
  {
    name: "天翼云盘",
    description: "中国电信天翼云盘官方入口，面向个人和家庭文件存储、备份与分享。",
    url: "https://cloud.189.cn/",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "TY",
    color: "linear-gradient(135deg, #ef4444, #f97316)",
  },
  {
    name: "中国移动云盘",
    description: "中国移动云盘官方入口，支持文件备份、同步、在线查看和客户端下载。",
    url: "https://yun.139.com/",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "CM",
    color: "linear-gradient(135deg, #16a34a, #0ea5e9)",
  },
  {
    name: "115 网盘",
    description: "115 官方入口，提供云存储、文件管理、在线播放和多端访问。",
    url: "https://115.com/",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "115",
    color: "linear-gradient(135deg, #1d4ed8, #111827)",
  },
  {
    name: "坚果云",
    description: "坚果云官方客户端下载入口，主打多端同步、团队协作和文件共享。",
    url: "https://www.jianguoyun.com/s/downloads",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "JG",
    color: "linear-gradient(135deg, #7c2d12, #f59e0b)",
  },
  {
    name: "123网盘",
    description: "123云盘官方入口，提供云存储、文件管理、在线播放和多端访问。",
    aliases: ["123云盘", "123盘", "123pan"],
    url: "https://www.123pan.com/",
    category: "cloud-drive",
    categoryLabel: "国内网盘",
    initials: "12",
    color: "linear-gradient(135deg, #1e40af, #3b82f6)",
  },
  {
    name: "Microsoft 365 / Office",
    description: "Microsoft 365 官方入口，可访问 Word、Excel、PowerPoint、Outlook 等办公应用。",
    url: "https://www.office.com/",
    category: "office",
    categoryLabel: "办公服务",
    initials: "365",
    color: "linear-gradient(135deg, #f25022, #7fba00 45%, #00a4ef)",
  },
  {
    name: "Excel",
    iconUrl: "assets/icons/excel.svg",
    description: "Microsoft Excel 官方入口，用于电子表格、数据分析和在线协作。",
    url: "https://www.microsoft.com/en-us/microsoft-365/excel",
    category: "office",
    categoryLabel: "办公服务",
    initials: "XL",
    color: "linear-gradient(135deg, #107c41, #21a366)",
  },
  {
    name: "LibreOffice",
    description: "LibreOffice 官方下载入口，开源办公套件，包含 Writer、Calc、Impress 等组件。",
    url: "https://www.libreoffice.org/download/download-libreoffice/",
    category: "office",
    categoryLabel: "办公服务",
    initials: "LO",
    color: "linear-gradient(135deg, #18a303, #0f6b2f)",
  },
  {
    name: "WPS",
    description: "金山办公 WPS 官方入口。",
    url: "https://www.wps.cn/",
    category: "office",
    categoryLabel: "办公服务",
    initials: "WPS",
    color: "linear-gradient(135deg, #e7392e, #ff7a59)",
  },
  {
    name: "香蕉锐方-蓝条-绿线9",
    category: "other",
    categoryLabel: "其他",
    videoSrc: "assets/videos/banana-climbing.mp4",
  },
  {
    name: "香蕉锐方-蓝条-黄线9(没过)",
    category: "other",
    categoryLabel: "其他",
    videoSrc: "assets/videos/climbing-1962.mp4",
  },
  {
    name: "香蕉锐方-蓝条-黄线9",
    category: "other",
    categoryLabel: "其他",
    videoSrc: "assets/videos/climbing-1872.mp4",
  },
];

const categoryNames = {
  browser: "浏览器",
  remote: "远程控制",
  network: "网络工具",
  "china-ai": "国内 AI",
  "global-ai": "国外 AI",
  "music-ai": "音乐 AI",
  dev: "开发工具",
  "ai-dependency": "AI 依赖",
  office: "办公服务",
  "cloud-drive": "国内网盘",
  other: "其他",
};

const galleryPhotos = [
  { src: "assets/gallery/IMG_5862.JPG", alt: "烤鸭照片 1" },
  { src: "assets/gallery/hero-photo.jpg", alt: "烤鸭照片 2" },
];
