import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

// Run after adding/replacing an icon: node scripts/build-icons.mjs
const directory = new URL('../assets/icons/', import.meta.url);
const mimeTypes = { png: 'image/png', jpg: 'image/jpeg', svg: 'image/svg+xml' };
const icons = {};
for (const name of readdirSync(directory).sort()) {
  const mime = mimeTypes[name.split('.').at(-1)];
  if (!mime) continue;
  icons[`assets/icons/${name}`] = `data:${mime};base64,${readFileSync(new URL(name, directory)).toString('base64')}`;
}
writeFileSync(new URL('../js/icons.js', import.meta.url),
  '// Generated by node scripts/build-icons.mjs; edit assets/icons/ instead.\n' +
  `const embeddedIcons = ${JSON.stringify(icons, null, 2)};\n`);
console.log(`Bundled ${Object.keys(icons).length} icons.`);
